refactor: only set tsconfig.json as the default if the file exists
Otherwise give a better error that the user needs to set the tsconfig attribute.
Previously the error was

```
ERROR: /home/alexeagle/Projects/bazel-examples/next.js/lib/BUILD.bazel:3:11: Copying file lib/tsconfig.json failed: missing input file '//lib:tsconfig.json'
```

Also fix an error where the validator read tsconfig from bazel-out