fix(ts_proto_library): require explicit srcs to copy (#617)
* Example on bazel failing when 2 ts_proto_library are in a single BUILD file

error: `Error in directory_path: directory_path rule '_logger_pb.d.ts_dirpath' in package 'examples/proto_grpc' conflicts with existing directory_path rule`

* fix: explicit files_to_copy for multiple ts_proto_lib

* fix(ts_proto_library): require explicit srcs to copy

The hack of using a glob over the srcs causes a collision when there is more than one ts_proto_library in a bazel package.
The resulting error doesn't give a clue what fix is required.

* chore: docgen

* fix: docs

---------

Co-authored-by: egorm <egorm@google.com>